# Server settings
server.port=8080

spring.application.name=application
spring.datasource.url=jdbc:h2:mem:bankingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Set logging level
logging.level.com.jpmorgan.challenge=INFO

# Log to a file
logging.file.name=logs/application.log


# OAuth2 Client Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/mock-auth
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/.well-known/jwks.json

spring.security.oauth2.resourceserver.jwt.secret=my-secret-key